name: linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install --ignore-engines
      - name: build production project
        run: yarn run build:prod
        if: always()
      - name: linting typescript
        run: yarn run lint:ts
        if: always()
      - name: linting css
        run: yarn run lint:scss
        if: always()
      - name: unit testing
        run: yarn run test:unit
        if: always()
      - name: build storybook
        run: yarn run storybook:build
        if: always()
      - name: screenshot testing
        run: yarn run test:ui:ci
        if: always()